config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :account, controllers: {
    confirmations: 'accounts/confirmations',
    passwords: 'accounts/passwords',
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    unlocks: 'accounts/unlocks'
  }

  resources :dashboard, only: [:index]

  resources :profile, only: [:show]
  resources :friends, only: [:index]

  namespace :my do
    resources :health, only: [:index]
    namespace :health do
      resources :sleeps, only: %i[index show new create edit update]
      resources :body_weights, only: %i[index show new create edit update]
      resources :body_measures, only: %i[index show new create edit update]
      resources :meditations, only: %i[index show new create edit update]
    end

    resources :activity, only: [:index]
    namespace :activity do
      resources :gym, only: [:index]
      resources :runnings, only: %i[index show new create edit update]
      resources :outdoor_walks, only: %i[index show new create edit update]
      resources :cycling, only: [:index]
      resources :yoga, only: [:index]
      namespace :yoga do
        resources :asanas, only: %i[index show new create edit update]
        resources :pranayama, only: [:index]
        resources :uddiyana, only: [:index]
        resources :affirmation, only: [:index]
      end
      resources :custom_workouts, only: %i[index show new create edit update]
    end

    resources :learning, only: [:index]
    namespace :learning do
      resources :videos, only: %i[index show new create edit update]
      resources :podcasts, only: %i[index show new create edit update]
      resources :articles, only: %i[index show new create edit update]
      resources :books, only: %i[index show new create edit update]
    end
  end

  root 'home#index'
end

app/controllers/my/learning/articles_controller.rb
# frozen_string_literal: true

module My
  module Learning
    class ArticlesController < BaseController
      include Import[service: 'learning.articles.service']

      def index
        super
      end

      def show
        super
      end

      def new
        super
      end

      def create
        super { my_learning_articles_path }
      end

      def edit
        super
      end

      def update
        super { my_learning_articles_path }
      end

      private

      def resource_params
        params.require(:learning_article)
              .permit(:url, :title, :feeling, :notes, :created_at)
              .to_h.symbolize_keys
      end

      def resource_class
        current_account.learning_article
      end
    end
  end
end

app/controllers/my/learning/base_controller.rb
# frozen_string_literal: true

module My
  module Learning
    class BaseController < ApplicationController
    end
  end
end

app/controllers/my/learning/books_controller.rb
# frozen_string_literal: true

module My
  module Learning
    class BooksController < BaseController
      include Import[service: 'learning.books.service']

      def index
        super
      end

      def show
        super
      end

      def new
        super
      end

      def create
        super { my_learning_books_path }
      end

      def edit
        super
      end

      def update
        super { my_learning_books_path }
      end

      private

      def resource_params
        params.require(:learning_book)
              .permit(:title, :author, :url, :status, :feeling, :notes, :created_at)
              .to_h.symbolize_keys
      end

      def resource_class
        current_account.learning_book
      end
    end
  end
end

app/controllers/my/learning/podcasts_controller.rb
# frozen_string_literal: true

module My
  module Learning
    class PodcastsController < BaseController
      include Import[service: 'learning.podcasts.service']

      def index
        super
      end

      def show
        super
      end

      def new
        super
      end

      def create
        super { my_learning_podcasts_path }
      end

      def edit
        super
      end

      def update
        super { my_learning_podcasts_path }
      end

      private

      def resource_params
        params.require(:learning_podcast)
              .permit(:url, :title, :feeling, :notes, :created_at)
              .to_h.symbolize_keys
      end

      def resource_class
        current_account.learning_podcast
      end
    end
  end
end

app/controllers/my/learning/videos_controller.rb
# frozen_string_literal: true

module My
  module Learning
    class VideosController < BaseController
      include Import[service: 'learning.videos.service']

      def index
        super
      end

      def show
        super
      end

      def new
        super
      end

      def create
        super { my_learning_videos_path }
      end

      def edit
        super
      end

      def update
        super { my_learning_videos_path }
      end

      private

      def resource_params
        params.require(:learning_video)
              .permit(:url, :title, :feeling, :notes, :created_at)
              .to_h.symbolize_keys
      end

      def resource_class
        current_account.learning_video
      end
    end
  end
end

app/controllers/my/learning_controller.rb
# frozen_string_literal: true

module My
  class LearningController < BaseController
    def index; end
  end
end

app/views/my/learning/videos/_form.html.slim
= render partial: 'shared/validation_errors', locals: { model: video, errors: local_assigns[:errors].presence }

= form_for [:my, video] do |f|
  .form-group.row
    = f.label :created_at, class: 'col-4 col-lg-3 col-form-label'
    .col-8.col-sm-5.col-md-4
      = f.text_field :created_at, class: 'form-control created-at'

  .form-group.row
    = f.label :url, class: 'col-4 col-lg-3 col-form-label'
    .col.col-lg-8
      = f.text_field :url, class: 'form-control', required: 'required', min: 0

  .form-group.row
    = f.label :title, class: 'col-4 col-lg-3 col-form-label'
    .col.col-lg-8
      = f.text_field :title, class: 'form-control', max: 100
      small.form-text.text-muted
        | (100 characters maximum)

  = render partial: 'shared/feeling', locals: { form: f, value: video.feeling }
  = render partial: 'shared/notes', locals: { form: f }

  .form-group.row
    .col-4.col-lg-3
    .col-8
      = f.submit t('shared.buttons.save'), class: 'btn btn-success'

app/views/my/learning/videos/edit.html.slim
- title = t('views.my.learning.video.edit.title')
- content_for :title, title

h2 = title

= render 'form', video: @record, errors: @errors

app/views/my/learning/videos/index.html.slim
- title = t('views.my.learning.video.index.title')
- content_for :title, title

h2 = title

.row
  .col-sm-4
    = link_to(new_my_learning_video_path, class: 'btn btn-success')
      = t('shared.buttons.add_new')

br

.row
  .col
    table#learning_videos.table.table-sm.table-hover
      thead.thead-light
        tr
          th scope="col" Title
          th scope="col" Feeling
          th scope="col" Created at
          th scope="col"

      tbody
        - @records.each do |video|
          - video_presenter = Learning::VideoPresenter.new(video)
          tr
            td scope="row" = video_presenter.clickable_title
            td = video.feeling
            td = human_readable_date(video.created_at)
            td.text-right
              = link_to(edit_my_learning_video_path(video), class: 'btn btn-secondary btn-sm')
                = fa_icon('edit')

    == pagy_bootstrap_nav @pagy

app/views/my/learning/videos/new.html.slim
- title = t('views.my.learning.video.new.title')
- content_for :title, title

h2 = title

= render 'form', video: @record, errors: @errors

app/views/my/learning/videos/show.html.slim
- title = t('views.my.learning.video.show.title')
- content_for :title, title
- video_presenter = Learning::VideoPresenter.new(@record)

h2 = video_presenter.clickable_title

= image_tag('placeholders/360x240.png', class: 'img-thumbnail')

p#notes = @record.notes.html_safe