config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :account, controllers: {
    confirmations: 'accounts/confirmations',
    passwords: 'accounts/passwords',
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    unlocks: 'accounts/unlocks'
  }

  resources :dashboard, only: [:index]

  resources :profile, only: [:show]
  resources :friends, only: [:index]

  namespace :my do
    resources :health, only: [:index]
    namespace :health do
      resources :sleeps, only: %i[index show new create edit update]
      resources :body_weights, only: %i[index show new create edit update]
      resources :body_measures, only: %i[index show new create edit update]
      resources :meditations, only: %i[index show new create edit update]
    end

    resources :activity, only: [:index]
    namespace :activity do
      resources :gym, only: [:index]
      resources :runnings, only: %i[index show new create edit update]
      resources :outdoor_walks, only: %i[index show new create edit update]
      resources :cycling, only: [:index]
      resources :yoga, only: [:index]
      namespace :yoga do
        resources :asanas, only: %i[index show new create edit update]
        resources :pranayama, only: [:index]
        resources :uddiyana, only: [:index]
        resources :affirmation, only: [:index]
      end
      resources :custom_workouts, only: %i[index show new create edit update]
    end

    resources :learning, only: [:index]
    namespace :learning do
      resources :videos, only: %i[index show new create edit update]
      resources :podcasts, only: %i[index show new create edit update]
      resources :articles, only: %i[index show new create edit update]
      resources :books, only: %i[index show new create edit update]
    end
  end

  root 'home#index'
end

app/controllers/my/health/base_controller.rb
# frozen_string_literal: true

module My
  module Health
    class BaseController < ApplicationController
    end
  end
end

app/controllers/my/health/body_measures_controller.rb
# frozen_string_literal: true

module My
  module Health
    class BodyMeasuresController < BaseController
      include Import['find_for_specific_day', service: 'health.body_measures.service']

      def index
        super
      end

      def show
        super
      end

      def new
        created_today = find_for_specific_day.call(resource.new, Date.current)
        if created_today
          redirect_to edit_my_health_body_measure_path(created_today)
        else
          @record = resource.new
        end
      end

      def create
        super { my_health_body_measures_path }
      end

      def edit
        super
      end

      def update
        super { my_health_body_measures_path }
      end

      private

      def resource_params
        params.require(:health_body_measure)
              .permit(:chest, :waist, :hips, :unit, :feeling, :notes, :created_at)
              .to_h.symbolize_keys
      end

      def resource_class
        current_account.health_body_measure
      end
    end
  end
end

app/controllers/my/health/body_weights_controller.rb
# frozen_string_literal: true

module My
  module Health
    class BodyWeightsController < BaseController
      include Import['find_for_specific_day', service: 'health.body_weights.service']

      def index
        super
      end

      def show
        super
      end

      def new
        created_today = find_for_specific_day.call(resource.new, Date.current)
        if created_today
          redirect_to edit_my_health_body_weight_path(created_today)
        else
          @record = resource.new
        end
      end

      def create
        super { my_health_body_weights_path }
      end

      def edit
        super
      end

      def update
        super { my_health_body_weights_path }
      end

      private

      def resource_params
        params.require(:health_body_weight)
              .permit(:weight, :unit, :feeling, :notes, :created_at)
              .to_h.symbolize_keys
      end

      def resource_class
        current_account.health_body_weight
      end
    end
  end
end

app/controllers/my/health/meditations_controller.rb
# frozen_string_literal: true

module My
  module Health
    class MeditationsController < BaseController
      include Import[service: 'health.meditations.service']

      def index
        super
      end

      def show
        super
      end

      def new
        super
      end

      def create
        super { my_health_meditations_path }
      end

      def edit
        super
      end

      def update
        super { my_health_meditations_path }
      end

      private

      def resource_params
        params.require(:health_meditation)
              .permit(:notes, :feeling, :created_at)
              .to_h.symbolize_keys
      end

      def resource_class
        current_account.health_meditation
      end
    end
  end
end

app/controllers/my/health/sleeps_controller.rb
# frozen_string_literal: true

module My
  module Health
    class SleepsController < BaseController
      include Import['find_for_specific_day', service: 'health.sleeps.service']

      def index
        super
      end

      def show
        super
      end

      def new
        created_today = find_for_specific_day.call(resource.new, Date.current)
        if created_today
          redirect_to edit_my_health_sleep_path(created_today)
        else
          @record = resource.new
        end
      end

      def create
        super { my_health_sleeps_path }
      end

      def edit
        super
      end

      def update
        super { my_health_sleeps_path }
      end

      private

      def resource_params
        params.require(:health_sleep)
              .permit(:woke_up_at_hour, :woke_up_at_minutes, :feeling, :notes, :created_at)
              .to_h.symbolize_keys
      end

      def resource_class
        current_account.health_sleep
      end
    end
  end
end

app/controllers/my/health_controller.rb
# frozen_string_literal: true

module My
  class HealthController < BaseController
    def index; end
  end
end

app/views/my/health/meditations/_form.html.slim
= render partial: 'shared/validation_errors', locals: { model: meditation, errors: local_assigns[:errors].presence }

= form_for [:my, meditation] do |f|
  .form-group.row
    = f.label :created_at, class: 'col-4 col-lg-3 col-form-label'
    .col-8.col-sm-5.col-md-4
      = f.text_field :created_at, class: 'form-control created-at'

  = render partial: 'shared/notes', locals: { form: f, required: true }
  = render partial: 'shared/feeling', locals: { form: f, value: meditation.feeling }

  .form-group.row
    .col-4.col-lg-3
    .col-8
      = f.submit t('shared.buttons.save'), class: 'btn btn-success'

app/views/my/health/meditations/edit.html.slim
- title = t('views.my.health.meditation.edit.title')
- content_for :title, title

h2 = title

= render 'form', meditation: @record, errors: @errors

app/views/my/health/meditations/index.html.slim
- title = t('views.my.health.meditation.index.title')
- content_for :title, title

h2 = title

.row
  .col-sm-4
    = link_to(new_my_health_meditation_path, class: 'btn btn-success')
      = t('shared.buttons.add_new')

br

.row
  .col
    table#health_meditations.table.table-sm.table-hover
      thead.thead-light
        tr
          th scope="col" Notes
          th scope="col" Feeling
          th scope="col" Created at
          th scope="col"

      tbody
        - @records.each do |meditation|
          tr
            td scope="row" = meditation.notes
            td = meditation.feeling
            td = human_readable_date(meditation.created_at)
            td.text-right
              = link_to(edit_my_health_meditation_path(meditation), class: 'btn btn-secondary btn-sm')
                = fa_icon('edit')

    == pagy_bootstrap_nav @pagy

app/views/my/health/meditations/new.html.slim
- title = t('views.my.health.meditation.new.title')
- content_for :title, title

h2 = title

= render 'form', meditation: @record, errors: @errors

app/views/my/health/meditations/show.html.slim
- title = t('views.my.health.meditation.show.title')
- content_for :title, title

p#notes = @record.notes.html_safe